apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000       # <-- Змінено на 3000
      targetPort: 3000 # <-- Змінено на 3000
      nodePort: 30001