apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort # Використовуємо NodePort для доступу ззовні Minikube
  ports:
    - protocol: TCP
      port: 80       # Порт, який сервіс відкриває всередині кластера
      targetPort: 80 # Порт контейнера, на який перенаправляє сервіс
      nodePort: 30001 # Можна вказати конкретний NodePort (30000-32767), або Minikube вибере сам