apiVersion: v1
kind: Service
metadata:
  name: demo6-backend-service # Ім'я сервісу
spec:
  selector:
    app: demo6-backend # Має відповідати labels у deployment.yaml
  ports:
    - protocol: TCP
      port: 8080       # <--- Змінено на 8080 (порт сервісу в кластері)
      targetPort: 8080 # Порт, який слухає контейнер вашого додатку
      nodePort: 30080  # <--- Додано NodePort, оберіть будь-який вільний порт в діапазоні 30000-32767
  type: NodePort # Дозволяє доступ ззовні кластера Minikube